name: Test Python Script

on:
    # ワークフロートリガーは、プルリク発行 or プッシュ時
    pull_request: 
        types: opened
    push:

jobs:
    test_python_script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # 実行に必要なpythonライブラリをインストール
            - run:
                pip install -r src/requirements.txt
            # テスト実行
            - run:
                python3 src/lambda_function.py ${{ secrets.SLACK_WEBHOOK }}
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
